In [4]:
#check numpy version 
import numpy as np
np.__version__
#1d,2d,3d,4d
# np._vesion_

'2.3.0'

In [6]:
lst = [1,2,3,4,5]
ar1 = np.array(lst)
ar1
#print(type(ar1))

array([1, 2, 3, 4, 5])

In [8]:
ar2 = np.arange(1,10)
ar2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
arr3 = np.ones(5)
arr3

array([1., 1., 1., 1., 1.])

In [16]:
arr5 = np.linspace(1,20,50)
arr5

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [18]:
## 2d array
arr6 = np.arange(1,31).reshape(5,6) ## araange the krta hai yani 2d and rwow and coloumn.
arr6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [25]:
arr7 = np.random.random(10)
arr7

array([0.2078586 , 0.45554973, 0.13107787, 0.44604759, 0.92582824,
       0.9024221 , 0.95273424, 0.36262647, 0.36497797, 0.18563785])

In [26]:
arr7 = np.random.randint(1,100,10)
arr7

array([35, 92, 32, 37, 76, 30, 58, 28, 51, 56], dtype=int32)

In [43]:
arr8 = np.arange(60).reshape(12,5)
arr8
# arr8.shape
# arr8.dtype
# arr8.size
# arr8.ndim

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
#multidimension array convert  1d
arr8.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [7]:
arr7  = np.array([2,5,1,9])
arr7.argsort()
arr7*2

array([ 4, 10,  2, 18])